### ISSUE TITLE
Error in mounted hook: "TypeError: this.control.summernote is not a function"

### ISSUE THREAD

**Issue by webafra** [malisit/vuejs2-wysiwyg#2]
hello and thanks for this package .

i want use this component on my vue spa project but show this error : 

Error in mounted hook: "TypeError: this.control.summernote is not a function"

Vue version : 3.2.3 
node v : v10.15.0

**Comment by malisit** [comment]
Hi,

Unfortunately this package only supports vue version 2.0.0^.
